apiVersion: v1
kind: ConfigMap
metadata:
  name: kluctl-notifications-cm
data:
  trigger.on-reconciliation: |
    - when: any(kluctldeployment.status.conditions, {.type == "Ready"}) && any(kluctldeployment.status.conditions, {.status == "True"})
      send: [deployment-ready]
    - when: any(kluctldeployment.status.conditions, {.type == "Ready"}) && any(kluctldeployment.status.conditions, {.status == "False"})
      send: [deployment-failed]

  service.webhook.slack_webhook: |
    url: $slack-webhook-url
    headers:
    - name: Content-Type
      value: application/json

  template.deployment-ready: |
    webhook:
      slack_webhook:
        method: POST
        body: |
          {
            "attachments": [{
              "title": "{{ .kluctldeployment.spec.target }}",
              "color": "#18be52",
              "fields": [{
                "title": "Sync Status",
                "value": '{{ index .kluctldeployment.status.conditions 0 "message" }}',
                "short": false
              }, {
                "title": "Result",
                "value": "http://localhost:8080?commandResultId={{ .kluctldeployment.status.lastDeployResult.id }}",
                "short": false
              }, {
                "title": "Repository",
                "value": "{{ .kluctldeployment.status.lastDeployResult.gitInfo.url }}",
                "short": false
              }]
            }]
          }

  template.deployment-failed: |
    webhook:
      slack_webhook:
        method: POST
        body: |
          {
            "attachments": [{
              "title": "{{ .kluctldeployment.spec.target }}",
              "color": "#e31429",
              "fields": [{
                "title": "Sync Status",
                "value": '{{ index .kluctldeployment.status.lastValidateResult.errors 0 "message" }}',
                "short": false
              }, {
                "title": "Result",
                "value": "http://localhost:8080?commandResultId={{ .kluctldeployment.status.lastDeployResult.id }}",
                "short": false
              }, {
                "title": "Repository",
                "value": "{{ .kluctldeployment.status.lastDeployResult.gitInfo.url }}",
                "short": false
              }]
            }]
          }